### ISSUE TITLE
Embedded multiple chached charts with iframe

### ISSUE THREAD

**Issue by KFredberg** [mindspank/chartcacher#4]
When I try to embedded more than one chached chart in a html document, they all show the same chart. I use iframe to embed.

**Comment by mindspank** [comment]
I have been trying to replicate this but I'm unable to do so.
Tested with multiple charts from different apps, from same apps, with and without the /nocache switch but they all render fine.

Can you provide some more details around the issue?

**Comment by KFredberg** [comment]
I can't replicate it either, and now it works. 
When it appeared I thought it was the browser cache. But I tried both firefox, chrome and explorer and all three browser showed the same chart.
